version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql_controle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_usuarios
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build: .
    container_name: api_controle
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - .env
volumes:
  mysql_data: