version: '3.9'

services:

  api:
    build: .
    container_name: controle-usuarios-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - mysql

    volumes:
      - .:/app

    command: npm run dev

  mysql:
    image: mysql:8

    container_name: mysql-controle-usuarios

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_usuarios

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: